# Site settings
title: High-throughput chemical genomics in the Banzhaf Laboratory at Newcastle University
lab_name: Banzhaf Laboratory
author: >
  Huda Ahmad, Manuel Banzhaf, and the Banzhaf Lab
institution: Newcastle University
email: manuel.banzhaf@ncl.ac.uk
description: >
  The Banzhaf Laboratory develops high-throughput chemical genomics approaches 
  to study pathogen phenotypes, gene function, and the bacterial cell envelope.
baseurl: ""
url: "https://hudaahmadd.github.io"
twitter_username: BanzhafLab
github_username:  hudaahmadd
images_dir: "/images/"

# Build settings
markdown: kramdown
include: ["_pages"]
permalink: /:title/

#plugins for search engine optimization
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
